import type { TemplateInput } from './template.ts';

/** Templates created on first run. Users can edit or duplicate them like any other. */
export const STARTER_TEMPLATES: TemplateInput[] = [
  {
    name: 'Video games',
    description: 'Games on any platform, with playtime, condition and value.',
    icon: 'gamepad',
    accessionPrefix: 'VG',
    fields: [
      {
        id: 'platform',
        label: 'Platform',
        type: 'choice',
        options: {
          choices: [
            'Switch',
            'Switch 2',
            'PS5',
            'PS4',
            'PS3',
            'PS2',
            'PS1',
            'Xbox Series',
            'Xbox One',
            'Xbox 360',
            'GameCube',
            'Wii',
            'Wii U',
            '3DS',
            'DS',
            'Game Boy',
            'PC',
            'Other',
          ],
        },
      },
      { id: 'developer', label: 'Developer', type: 'text' },
      { id: 'release_year', label: 'Release year', type: 'number' },
      { id: 'genre', label: 'Genre', type: 'tags' },
      { id: 'edition', label: 'Edition', type: 'text' },
      {
        id: 'condition',
        label: 'Condition',
        type: 'choice',
        options: { choices: ['Sealed', 'Mint', 'Very good', 'Good', 'Fair', 'Poor'] },
      },
      {
        id: 'status',
        label: 'Status',
        type: 'choice',
        options: { choices: ['Not started', 'Playing', 'Completed', 'Abandoned'] },
      },
      { id: 'main_story', label: 'Main story', type: 'duration' },
      { id: 'completionist', label: 'Completionist', type: 'duration' },
      { id: 'acquired', label: 'Acquired', type: 'date' },
      { id: 'price_paid', label: 'Price paid', type: 'money', options: { currency: 'EUR' } },
      { id: 'value', label: 'Value', type: 'money', options: { currency: 'EUR' } },
      { id: 'summary', label: 'Summary', type: 'longtext' },
      { id: 'notes', label: 'Notes', type: 'longtext' },
    ],
    card: {
      slots: { tl: 'platform', tr: '$accession', b: null },
      lines: [
        { fields: ['$title'], style: 'title' },
        { fields: ['platform', 'release_year'], style: 'muted' },
        { fields: ['value'], style: 'value' },
      ],
    },
    itemLayout: {
      info: [
        'platform',
        'developer',
        'release_year',
        'genre',
        'edition',
        'condition',
        'acquired',
        'price_paid',
        'value',
      ],
      sections: [
        { id: 'summary', type: 'text', title: 'Summary', fields: ['summary'], wide: true },
        { id: 'playtime', type: 'fields', title: 'Playtime', fields: ['main_story', 'completionist', 'status'] },
        { id: 'notes', type: 'text', title: 'Notes', fields: ['notes'] },
      ],
    },
    header: {
      figures: [
        { id: 'count', kind: 'count', label: 'Items' },
        { id: 'value', kind: 'sum', label: 'Value', field: 'value' },
        { id: 'backlog', kind: 'countWhere', label: 'Backlog', field: 'status', equals: 'Not started' },
      ],
    },
  },
  {
    name: 'Books',
    description: 'Books with author, publisher, language, reading status and loans.',
    icon: 'book',
    accessionPrefix: 'BK',
    fields: [
      { id: 'subtitle', label: 'Subtitle', type: 'text' },
      { id: 'author', label: 'Author', type: 'text', required: true },
      { id: 'publisher', label: 'Publisher', type: 'text' },
      {
        id: 'language',
        label: 'Language',
        type: 'choice',
        options: { choices: ['ES', 'EN', 'CA', 'EU', 'GL', 'FR', 'DE', 'IT', 'PT', 'Other'] },
      },
      { id: 'isbn', label: 'ISBN', type: 'text' },
      { id: 'pages', label: 'Pages', type: 'number', options: { min: 1 } },
      { id: 'height_cm', label: 'Height', type: 'number', options: { unit: 'cm', min: 1, max: 100 } },
      { id: 'year_bought', label: 'Year bought', type: 'number' },
      {
        id: 'status',
        label: 'Status',
        type: 'choice',
        options: { choices: ['Unread', 'Reading', 'Read', 'Abandoned'] },
      },
      { id: 'rating', label: 'Rating', type: 'rating', options: { max: 5 } },
      { id: 'lent_to', label: 'Lent to', type: 'text' },
      { id: 'synopsis', label: 'Synopsis', type: 'longtext' },
      { id: 'notes', label: 'Notes', type: 'longtext' },
    ],
    card: {
      slots: { tl: 'language', tr: 'publisher', b: 'author' },
      lines: [
        { fields: ['$title'], style: 'title' },
        { fields: ['subtitle'], style: 'normal' },
        { fields: ['author'], style: 'muted' },
        { fields: ['year_bought'], style: 'muted', prefix: 'Bought ' },
      ],
    },
    itemLayout: {
      info: ['author', 'publisher', 'language', 'isbn', 'pages', 'status', 'rating', 'year_bought', 'lent_to'],
      sections: [
        { id: 'synopsis', type: 'text', title: 'Synopsis', fields: ['synopsis'], wide: true },
        { id: 'notes', type: 'text', title: 'Notes', fields: ['notes'] },
      ],
    },
    header: {
      figures: [
        { id: 'count', kind: 'count', label: 'Books' },
        { id: 'unread', kind: 'countWhere', label: 'Unread', field: 'status', equals: 'Unread' },
        { id: 'pages', kind: 'sum', label: 'Pages', field: 'pages' },
      ],
    },
  },
  {
    name: 'Vinyl',
    description: 'Records with artist, label, pressing and value.',
    icon: 'disc',
    accessionPrefix: 'VN',
    fields: [
      { id: 'artist', label: 'Artist', type: 'text', required: true },
      { id: 'label', label: 'Label', type: 'text' },
      { id: 'year', label: 'Year', type: 'number' },
      {
        id: 'format',
        label: 'Format',
        type: 'choice',
        options: { choices: ['LP', '2×LP', 'EP', '7"', '10"', 'Box set'] },
      },
      { id: 'weight_g', label: 'Weight', type: 'number', options: { unit: 'g' } },
      { id: 'genre', label: 'Genre', type: 'tags' },
      {
        id: 'condition',
        label: 'Condition',
        type: 'choice',
        options: { choices: ['Mint', 'Near mint', 'Very good +', 'Very good', 'Good', 'Fair', 'Poor'] },
      },
      { id: 'value', label: 'Value', type: 'money', options: { currency: 'EUR' } },
      { id: 'tracklist', label: 'Tracklist', type: 'longtext' },
      { id: 'notes', label: 'Notes', type: 'longtext' },
    ],
    card: {
      slots: { tl: 'format', tr: '$accession', b: null },
      lines: [
        { fields: ['$title'], style: 'title' },
        { fields: ['artist'], style: 'normal' },
        { fields: ['label', 'year'], style: 'muted' },
        { fields: ['value'], style: 'value' },
      ],
    },
    itemLayout: {
      info: ['artist', 'label', 'year', 'format', 'weight_g', 'genre', 'condition', 'value'],
      sections: [
        { id: 'tracklist', type: 'text', title: 'Tracklist', fields: ['tracklist'], wide: true },
        { id: 'notes', type: 'text', title: 'Notes', fields: ['notes'] },
      ],
    },
    header: {
      figures: [
        { id: 'count', kind: 'count', label: 'Records' },
        { id: 'value', kind: 'sum', label: 'Value', field: 'value' },
      ],
    },
  },
  {
    name: 'Board games',
    description: 'Board games with player counts, playing time and plays.',
    icon: 'dice',
    accessionPrefix: 'BG',
    fields: [
      { id: 'designer', label: 'Designer', type: 'text' },
      { id: 'publisher', label: 'Publisher', type: 'text' },
      { id: 'year', label: 'Year', type: 'number' },
      { id: 'min_players', label: 'Min players', type: 'number', options: { min: 1 } },
      { id: 'max_players', label: 'Max players', type: 'number', options: { min: 1 } },
      { id: 'play_time', label: 'Playing time', type: 'duration' },
      { id: 'played', label: 'Played', type: 'boolean' },
      { id: 'rating', label: 'Rating', type: 'rating', options: { max: 5 } },
      { id: 'notes', label: 'Notes', type: 'longtext' },
    ],
    card: {
      slots: { tl: 'year', tr: '$accession', b: null },
      lines: [
        { fields: ['$title'], style: 'title' },
        { fields: ['designer'], style: 'muted' },
        { fields: ['play_time'], style: 'muted' },
      ],
    },
    itemLayout: {
      info: ['designer', 'publisher', 'year', 'min_players', 'max_players', 'play_time', 'played', 'rating'],
      sections: [{ id: 'notes', type: 'text', title: 'Notes', fields: ['notes'], wide: true }],
    },
    header: {
      figures: [
        { id: 'count', kind: 'count', label: 'Games' },
        { id: 'unplayed', kind: 'countWhere', label: 'Unplayed', field: 'played', equals: false },
      ],
    },
  },
  {
    name: 'Blank',
    description: 'Just a title and a cover. Add the fields you need.',
    icon: 'square',
    accessionPrefix: 'IT',
    fields: [{ id: 'notes', label: 'Notes', type: 'longtext' }],
    card: { slots: { tl: null, tr: '$accession', b: null }, lines: [{ fields: ['$title'], style: 'title' }] },
    itemLayout: { info: ['$added'], sections: [{ id: 'notes', type: 'text', title: 'Notes', fields: ['notes'] }] },
    header: { figures: [{ id: 'count', kind: 'count', label: 'Items' }] },
  },
];
